# alias bepo='sudo loadkeys /usr/share/keymaps/i386/dvorak/dvorak-fr-bepo.kmap.gz'
alias bepo='sudo loadkeys ~/files/kmaps/mybepo.kmap.gz'
alias cachemake='PATH=/usr/lib/ccache:$PATH cmake'
alias ctest='PATH=/usr/lib/ccache:$PATH ctest'
alias dcachemake='export CCACHE_PREFIX="distcc" ; cachemake -DCMAKE_CXX_COMPILER:FILEPATH=/usr/lib/ccache/x86_64-linux-gnu-g++-4.4 -DCMAKE_C_COMPILER:FILEPATH=/usr/lib/ccache/x86_64-linux-gnu-gcc-4.4'
alias dmake='PATH=/usr/lib/distcc:$PATH:/home/vincent/files/bin cmake -DCMAKE_CXX_COMPILER:FILEPATH=/usr/lib/distcc/x86_64-linux-gnu-g++-4.4 -DCMAKE_C_COMPILER:FILEPATH=/usr/lib/distcc/x86_64-linux-gnu-gcc-4.4'
alias dosbox_castle='dosbox -conf ~/.dosbox/castle_adventure.conf'
alias dtail='dmesg | tail'
alias dtali='dmesg | tail'
alias emacs='emacs -nw'
alias e='emacs'
alias gdbrun='/home/vincent/files/bin/utils/gdbrun'
alias greps='grep --exclude-dir .svn -n'
alias grepsb='grep --exclude-dir .svn --exclude-dir build -n'
alias isswallpaper='livestreamer http://www.ustream.tv/channel/iss-hdev-payload best -O | mplayer -  -rootwin -vf scale=1920:1200 -noconsolecontrols'
alias l='ls -la'
alias l='ls -la'
alias la='ls -A'
alias ll='ls -l'
alias ll='ls -ll'
alias makej='make -j `nproc` $*'
alias makejx='make -j `nproc` ; xeyes'
alias maket='ctest -j `nproc` $*'
alias makex='make ; xeyes'
alias makexp='maket -D Experimental'
alias makexpx='maket -D Experimental ; xeyes'
alias policy='zless /usr/share/doc/debian-policy/policy.txt.gz'
alias redshiftme='redshift -l 45.73313:4.82789 -t 5700:3600 -g 0.8 -m vidmode -v &'
alias rmtmp='rm -f *~ \#* ./.*~'
alias sidlogin='sudo pbuilder --login --no-targz  --debug --buildplace /sid-root'
alias slrnfree='LANG="fr_FR ISO-8859-1" slrn -f .jnewsrccomp'
alias slrnqt='NNTPSERVER=nntp.trolltech.com ; slrn -f /home/vincent/.jnewsrcqt'
alias st='svn st'
alias sync_key_to_pc='/home/vincent/key/scripts/sync_key_to_pc.sh'
alias sync_pc_to_key='/home/vincent/key/scripts/sync_pc_to_key.sh'
alias telnet='rlwrap telnet'
alias valgrinc='valgrind --suppressions=/home/vincent/files/projects/cosmo/git/csmSDK/csmCore/Utils/Valgrind/CoSMoKernelValgrind.supp --suppressions=/usr/lib/valgrind/debian-libc6-dbg.supp --suppressions=/usr/lib/valgrind/debian.supp --suppressions=/usr/lib/valgrind/default.supp -q --tool=memcheck --show-below-main=no --leak-check=yes --show-reachable=yes --num-callers=50 --fullpath-after=. $*'
alias xe='\emacs'
